# Generated by Django 4.2.5 on 2024-08-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orde',
            new_name='Order',
        ),
    ]
