# Generated by Django 4.2.5 on 2025-04-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_catogery_options_alter_product_image_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
