# Generated by Django 4.2.5 on 2025-04-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cateogery',
            new_name='catogery',
        ),
    ]
