# Generated by Django 4.2.5 on 2025-04-22 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_embedding_recommendationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catogery',
        ),
        migrations.AddField(
            model_name='product',
            name='Catogery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.catogery'),
        ),
    ]
