# Generated by Django 4.2.5 on 2025-04-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productvisit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvisit',
            options={'ordering': ['-visited_at']},
        ),
        migrations.AlterUniqueTogether(
            name='productvisit',
            unique_together=set(),
        ),
    ]
